/* Generated By:JavaCC: Do not edit this line. LibParserTokenManager.java */
package lib;

/** Token Manager. */
public class LibParserTokenManager implements LibParserConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x8L) != 0L)
         {
            jjmatchedKind = 53;
            return 124;
         }
         if ((active0 & 0x800L) != 0L)
            return 188;
         if ((active0 & 0x800000L) != 0L)
            return 84;
         if ((active0 & 0x10000000L) != 0L)
            return 32;
         if ((active0 & 0x2040L) != 0L)
         {
            jjmatchedKind = 53;
            return 134;
         }
         if ((active0 & 0x4400L) != 0L)
         {
            jjmatchedKind = 53;
            return 8;
         }
         if ((active0 & 0x210020L) != 0L)
         {
            jjmatchedKind = 53;
            return 174;
         }
         if ((active0 & 0x400200L) != 0L)
         {
            jjmatchedKind = 53;
            return 52;
         }
         if ((active0 & 0x1c9194L) != 0L)
         {
            jjmatchedKind = 53;
            return 189;
         }
         return -1;
      case 1:
         if ((active0 & 0x7df1fcL) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 1;
            return 190;
         }
         if ((active0 & 0x800L) != 0L)
            return 191;
         if ((active0 & 0x600L) != 0L)
            return 190;
         return -1;
      case 2:
         if ((active0 & 0x7df17cL) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 2;
            return 163;
         }
         if ((active0 & 0x80L) != 0L)
            return 163;
         return -1;
      case 3:
         if ((active0 & 0x1d0000L) != 0L)
            return 164;
         if ((active0 & 0x60f17cL) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 53;
               jjmatchedPos = 3;
            }
            return 164;
         }
         return -1;
      case 4:
         if ((active0 & 0x48503cL) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 4;
            return 165;
         }
         if ((active0 & 0x20a140L) != 0L)
            return 165;
         return -1;
      case 5:
         if ((active0 & 0x401000L) != 0L)
            return 166;
         if ((active0 & 0x8403cL) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 5;
            return 166;
         }
         return -1;
      case 6:
         if ((active0 & 0x84030L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 6;
            return 167;
         }
         if ((active0 & 0xcL) != 0L)
            return 167;
         return -1;
      case 7:
         if ((active0 & 0x80020L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 7;
            return 192;
         }
         if ((active0 & 0x4010L) != 0L)
            return 192;
         return -1;
      case 8:
         if ((active0 & 0x80020L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 8;
            return 192;
         }
         return -1;
      case 9:
         if ((active0 & 0x20L) != 0L)
            return 192;
         if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 9;
            return 192;
         }
         return -1;
      case 10:
         if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 10;
            return 192;
         }
         return -1;
      case 11:
         if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 11;
            return 192;
         }
         return -1;
      case 12:
         if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 12;
            return 192;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 34:
         return jjStartNfaWithStates_0(0, 23, 84);
      case 36:
         return jjStartNfaWithStates_0(0, 28, 32);
      case 40:
         return jjStopAtPos(0, 29);
      case 41:
         return jjStopAtPos(0, 30);
      case 44:
         return jjStopAtPos(0, 24);
      case 46:
         return jjStopAtPos(0, 27);
      case 65:
         return jjMoveStringLiteralDfa1_0(0x400200L);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x180010L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x1000L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x8080L);
      case 72:
         return jjMoveStringLiteralDfa1_0(0x100L);
      case 76:
         return jjMoveStringLiteralDfa1_0(0x4L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x4400L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x40000L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x2040L);
      case 84:
         return jjMoveStringLiteralDfa1_0(0x210020L);
      case 87:
         return jjMoveStringLiteralDfa1_0(0x8L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x800L);
      case 123:
         return jjStopAtPos(0, 25);
      case 125:
         return jjStopAtPos(0, 26);
      default :
         return jjMoveNfa_0(9, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000L);
      case 69:
         return jjMoveStringLiteralDfa2_0(active0, 0x8L);
      case 73:
         return jjMoveStringLiteralDfa2_0(active0, 0x200024L);
      case 76:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000L);
      case 77:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(1, 9, 190);
         else if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(1, 10, 190);
         return jjMoveStringLiteralDfa2_0(active0, 0x8000L);
      case 78:
         return jjMoveStringLiteralDfa2_0(active0, 0x80L);
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0x184100L);
      case 84:
         return jjMoveStringLiteralDfa2_0(active0, 0x2040L);
      case 85:
         return jjMoveStringLiteralDfa2_0(active0, 0x400010L);
      case 89:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000L);
      case 111:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(1, 11, 191);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa3_0(active0, 0xa040L);
      case 66:
         return jjMoveStringLiteralDfa3_0(active0, 0xcL);
      case 68:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(2, 7, 163);
         break;
      case 73:
         return jjMoveStringLiteralDfa3_0(active0, 0x10L);
      case 77:
         return jjMoveStringLiteralDfa3_0(active0, 0x20L);
      case 79:
         return jjMoveStringLiteralDfa3_0(active0, 0x181000L);
      case 80:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000L);
      case 83:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000L);
      case 84:
         return jjMoveStringLiteralDfa3_0(active0, 0x640000L);
      case 85:
         return jjMoveStringLiteralDfa3_0(active0, 0x100L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(3, 16, 164);
         else if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(3, 18, 164);
         return jjMoveStringLiteralDfa4_0(active0, 0x20L);
      case 70:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000L);
      case 72:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000L);
      case 73:
         return jjMoveStringLiteralDfa4_0(active0, 0xc000L);
      case 75:
         if ((active0 & 0x100000L) != 0L)
         {
            jjmatchedKind = 20;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x80000L);
      case 76:
         return jjMoveStringLiteralDfa4_0(active0, 0x200010L);
      case 82:
         return jjMoveStringLiteralDfa4_0(active0, 0x144L);
      case 83:
         return jjMoveStringLiteralDfa4_0(active0, 0x1008L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa5_0(active0, 0x4L);
      case 67:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000L);
      case 68:
         return jjMoveStringLiteralDfa5_0(active0, 0x10L);
      case 69:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(4, 21, 165);
         return jjMoveStringLiteralDfa5_0(active0, 0x1000L);
      case 70:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(4, 13, 165);
         break;
      case 73:
         return jjMoveStringLiteralDfa5_0(active0, 0x8L);
      case 76:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(4, 15, 165);
         break;
      case 79:
         return jjMoveStringLiteralDfa5_0(active0, 0x400020L);
      case 83:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(4, 8, 165);
         break;
      case 84:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(4, 6, 165);
         return jjMoveStringLiteralDfa5_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 68:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(5, 12, 166);
         break;
      case 70:
         return jjMoveStringLiteralDfa6_0(active0, 0x20L);
      case 73:
         return jjMoveStringLiteralDfa6_0(active0, 0x4010L);
      case 79:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000L);
      case 82:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(5, 22, 166);
         return jjMoveStringLiteralDfa6_0(active0, 0x4L);
      case 84:
         return jjMoveStringLiteralDfa6_0(active0, 0x8L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(6, 3, 167);
         break;
      case 76:
         return jjMoveStringLiteralDfa7_0(active0, 0x80000L);
      case 78:
         return jjMoveStringLiteralDfa7_0(active0, 0x10L);
      case 79:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000L);
      case 89:
         if ((active0 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(6, 2, 167);
         return jjMoveStringLiteralDfa7_0(active0, 0x20L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa8_0(active0, 0x20L);
      case 71:
         if ((active0 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(7, 4, 192);
         break;
      case 76:
         return jjMoveStringLiteralDfa8_0(active0, 0x80000L);
      case 78:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(7, 14, 192);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa9_0(active0, 0x20L);
      case 69:
         return jjMoveStringLiteralDfa9_0(active0, 0x80000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa10_0(active0, 0x80000L);
      case 82:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(9, 5, 192);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 84:
         return jjMoveStringLiteralDfa11_0(active0, 0x80000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa12_0(active0, 0x80000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 79:
         return jjMoveStringLiteralDfa13_0(active0, 0x80000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 78:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(13, 19, 192);
         break;
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 188;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 174:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 46)
                  {
                     if (kind > 54)
                        kind = 54;
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 162;
                  else if (curChar == 46)
                     jjCheckNAdd(155);
                  break;
               case 84:
                  if ((0x7ff200100000000L & l) != 0L)
                     jjCheckNAddTwoStates(82, 83);
                  if (curChar == 32)
                     jjCheckNAddTwoStates(80, 81);
                  break;
               case 134:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 46)
                  {
                     if (kind > 54)
                        kind = 54;
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 162;
                  else if (curChar == 46)
                     jjCheckNAdd(155);
                  break;
               case 190:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 46)
                     jjCheckNAdd(155);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 163;
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 165:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 46)
                     jjCheckNAdd(155);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 166;
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 9:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(7, 10);
                  else if ((0x100002600L & l) != 0L)
                  {
                     if (kind > 1)
                        kind = 1;
                     jjCheckNAdd(0);
                  }
                  else if (curChar == 34)
                     jjCheckNAddStates(11, 13);
                  else if (curChar == 36)
                     jjCheckNAdd(32);
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     jjCheckNAddStates(14, 18);
                  }
                  break;
               case 52:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 46)
                  {
                     if (kind > 54)
                        kind = 54;
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 162;
                  else if (curChar == 46)
                     jjCheckNAdd(155);
                  break;
               case 192:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 46)
                     jjCheckNAdd(155);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 124:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 46)
                  {
                     if (kind > 54)
                        kind = 54;
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 162;
                  else if (curChar == 46)
                     jjCheckNAdd(155);
                  break;
               case 163:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 46)
                     jjCheckNAdd(155);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 164;
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 166:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 46)
                     jjCheckNAdd(155);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 167;
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 188:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 46)
                     jjCheckNAdd(155);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 191:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 46)
                     jjCheckNAdd(155);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 163;
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 164:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 46)
                     jjCheckNAdd(155);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 165;
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 8:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 46)
                  {
                     if (kind > 54)
                        kind = 54;
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 162;
                  else if (curChar == 46)
                     jjCheckNAdd(155);
                  break;
               case 167:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 46)
                     jjCheckNAdd(155);
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 49)
                        kind = 49;
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 189:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 46)
                  {
                     if (kind > 54)
                        kind = 54;
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 162;
                  else if (curChar == 46)
                     jjCheckNAdd(155);
                  break;
               case 0:
                  if ((0x100002600L & l) == 0L)
                     break;
                  if (kind > 1)
                     kind = 1;
                  jjCheckNAdd(0);
                  break;
               case 5:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 31:
                  if (curChar == 36)
                     jjCheckNAdd(32);
                  break;
               case 32:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 48)
                     kind = 48;
                  jjCheckNAddTwoStates(32, 33);
                  break;
               case 33:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 34:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 35:
                  if ((0x3ff000000000000L & l) != 0L && kind > 48)
                     kind = 48;
                  break;
               case 62:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 79:
                  if (curChar == 34)
                     jjCheckNAddStates(11, 13);
                  break;
               case 80:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(80, 81);
                  break;
               case 81:
                  if (curChar == 34 && kind > 32)
                     kind = 32;
                  break;
               case 82:
                  if ((0x7ff200100000000L & l) != 0L)
                     jjCheckNAddTwoStates(82, 83);
                  break;
               case 83:
                  if (curChar == 34 && kind > 50)
                     kind = 50;
                  break;
               case 85:
                  if (curChar == 47)
                     jjCheckNAddTwoStates(86, 87);
                  break;
               case 86:
                  if ((0xe00000000000L & l) != 0L)
                     jjCheckNAddTwoStates(86, 87);
                  break;
               case 87:
                  if (curChar == 34 && kind > 36)
                     kind = 36;
                  break;
               case 88:
               case 93:
                  if (curChar == 47)
                     jjCheckNAdd(85);
                  break;
               case 89:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 94:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 99:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  jjCheckNAddStates(14, 18);
                  break;
               case 100:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 101:
                  if ((0x3ff000000000000L & l) != 0L && kind > 34)
                     kind = 34;
                  break;
               case 102:
                  if ((0x3ff000000000000L & l) != 0L && kind > 40)
                     kind = 40;
                  break;
               case 103:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 104:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 105:
                  if ((0x3ff000000000000L & l) != 0L && kind > 41)
                     kind = 41;
                  break;
               case 106:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(107);
                  break;
               case 107:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 108:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 109:
                  if ((0x3ff000000000000L & l) != 0L && kind > 42)
                     kind = 42;
                  break;
               case 153:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(7, 10);
                  break;
               case 154:
                  if (curChar == 46)
                     jjCheckNAdd(155);
                  break;
               case 155:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 157:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjCheckNAddTwoStates(158, 160);
                  break;
               case 158:
                  if (curChar == 46)
                     jjCheckNAdd(159);
                  break;
               case 159:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjCheckNAddTwoStates(158, 159);
                  break;
               case 160:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjCheckNAddStates(19, 21);
                  break;
               case 161:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 162:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 163;
                  break;
               case 168:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  break;
               case 171:
                  if (curChar == 46 && kind > 54)
                     kind = 54;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 174:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 157;
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 53)
                        kind = 53;
                     jjCheckNAdd(170);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 162;
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 186;
                  else if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 180;
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 175;
                  else if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 173;
                  break;
               case 84:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(82, 83);
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(80, 81);
                  if (curChar == 104)
                     jjAddStates(22, 23);
                  break;
               case 134:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 157;
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 53)
                        kind = 53;
                     jjCheckNAdd(170);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 162;
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 151;
                  else if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 144;
                  else if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 140;
                  if (curChar == 117)
                     jjCheckNAdd(111);
                  else if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 190:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 157;
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 53)
                        kind = 53;
                     jjCheckNAdd(170);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 163;
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 165:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 157;
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 53)
                        kind = 53;
                     jjCheckNAdd(170);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 166;
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 9:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(7, 10);
                  if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 53)
                        kind = 53;
                     jjCheckNAddTwoStates(170, 171);
                  }
                  if (curChar == 84)
                     jjAddStates(24, 27);
                  else if (curChar == 83)
                     jjAddStates(28, 32);
                  else if (curChar == 87)
                     jjAddStates(33, 34);
                  else if (curChar == 77)
                     jjAddStates(35, 38);
                  else if (curChar == 70)
                     jjAddStates(39, 42);
                  else if (curChar == 65)
                     jjAddStates(43, 44);
                  else if (curChar == 74)
                     jjAddStates(45, 47);
                  else if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 29;
                  else if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 22;
                  else if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 15;
                  else if (curChar == 80)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 52:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 157;
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 53)
                        kind = 53;
                     jjCheckNAdd(170);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 162;
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 56;
                  else if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 192:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 157;
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 53)
                        kind = 53;
                     jjCheckNAdd(170);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 124:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 157;
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 53)
                        kind = 53;
                     jjCheckNAdd(170);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 162;
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 130;
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 163:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 157;
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 53)
                        kind = 53;
                     jjCheckNAdd(170);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 164;
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 166:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 157;
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 53)
                        kind = 53;
                     jjCheckNAdd(170);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 167;
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 188:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 157;
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 191:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 157;
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 163;
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 164:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 157;
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 53)
                        kind = 53;
                     jjCheckNAdd(170);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 165;
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 8:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 157;
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 53)
                        kind = 53;
                     jjCheckNAdd(170);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 162;
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 167:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 157;
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 53)
                        kind = 53;
                     jjCheckNAdd(170);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 49)
                        kind = 49;
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 189:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 157;
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 53)
                        kind = 53;
                     jjCheckNAdd(170);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 1:
                  if (curChar == 101 && kind > 17)
                     kind = 17;
                  break;
               case 2:
               case 59:
                  if (curChar == 109)
                     jjCheckNAdd(1);
                  break;
               case 3:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 4:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 6:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 7:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 10:
                  if (curChar == 114 && kind > 39)
                     kind = 39;
                  break;
               case 11:
               case 17:
               case 24:
               case 146:
                  if (curChar == 101)
                     jjCheckNAdd(10);
                  break;
               case 12:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 14:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 18:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 19:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 20:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 22:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 23:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 25:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 26:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 29:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 30:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 36:
                  if (curChar == 74)
                     jjAddStates(45, 47);
                  break;
               case 37:
                  if (curChar == 121 && kind > 39)
                     kind = 39;
                  break;
               case 38:
               case 73:
                  if (curChar == 114)
                     jjCheckNAdd(37);
                  break;
               case 39:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 40:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 41:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 42:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 43:
                  if (curChar == 101 && kind > 39)
                     kind = 39;
                  break;
               case 44:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 45:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 46:
                  if (curChar == 108)
                     jjCheckNAdd(37);
                  break;
               case 47:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 48:
                  if (curChar == 65)
                     jjAddStates(43, 44);
                  break;
               case 49:
                  if (curChar == 108 && kind > 39)
                     kind = 39;
                  break;
               case 50:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 51:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 53:
                  if (curChar == 116 && kind > 39)
                     kind = 39;
                  break;
               case 54:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 55:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 56:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 57:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 58:
                  if (curChar == 70)
                     jjAddStates(39, 42);
                  break;
               case 60:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 61:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 63:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 64:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 65:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 66:
                  if (curChar == 105 && kind > 37)
                     kind = 37;
                  break;
               case 67:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 68:
                  if (curChar == 121 && kind > 38)
                     kind = 38;
                  break;
               case 69:
               case 113:
               case 125:
               case 136:
               case 142:
               case 177:
               case 182:
                  if (curChar == 97)
                     jjCheckNAdd(68);
                  break;
               case 70:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 71:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 72:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 74:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 75:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 76:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 77:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 78:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 80:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(80, 81);
                  break;
               case 82:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(82, 83);
                  break;
               case 86:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjAddStates(48, 49);
                  break;
               case 90:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 91:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 92:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 95:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 96:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 97:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 98:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 110:
                  if (curChar == 77)
                     jjAddStates(35, 38);
                  break;
               case 111:
                  if (curChar == 110 && kind > 37)
                     kind = 37;
                  break;
               case 112:
                  if (curChar == 111)
                     jjCheckNAdd(111);
                  break;
               case 114:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 115:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 114;
                  break;
               case 116:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 117:
                  if (curChar == 104 && kind > 39)
                     kind = 39;
                  break;
               case 118:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 119:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 120:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 121:
                  if (curChar == 97)
                     jjCheckNAdd(37);
                  break;
               case 122:
                  if (curChar == 87)
                     jjAddStates(33, 34);
                  break;
               case 123:
                  if (curChar == 100 && kind > 37)
                     kind = 37;
                  break;
               case 126:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 127:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 128:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 129:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 128;
                  break;
               case 130:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 131:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 132:
                  if (curChar == 83)
                     jjAddStates(28, 32);
                  break;
               case 133:
                  if (curChar == 116 && kind > 37)
                     kind = 37;
                  break;
               case 135:
                  if (curChar == 117)
                     jjCheckNAdd(111);
                  break;
               case 137:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 138:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 137;
                  break;
               case 139:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 138;
                  break;
               case 140:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 141:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 143:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 142;
                  break;
               case 144:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 143;
                  break;
               case 145:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 147:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 146;
                  break;
               case 148:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 147;
                  break;
               case 149:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 148;
                  break;
               case 150:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 151:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 150;
                  break;
               case 152:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 153:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(7, 10);
                  break;
               case 155:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 156:
                  if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 157;
                  break;
               case 157:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjCheckNAddTwoStates(158, 160);
                  break;
               case 159:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjCheckNAddTwoStates(158, 159);
                  break;
               case 160:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjCheckNAddStates(19, 21);
                  break;
               case 161:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 162:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 163;
                  break;
               case 168:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  break;
               case 169:
                  if ((0x7fffffeL & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddTwoStates(170, 171);
                  break;
               case 170:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAdd(170);
                  break;
               case 172:
                  if (curChar == 84)
                     jjAddStates(24, 27);
                  break;
               case 173:
                  if (curChar == 101 && kind > 37)
                     kind = 37;
                  break;
               case 175:
                  if (curChar == 117 && kind > 37)
                     kind = 37;
                  break;
               case 176:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 175;
                  break;
               case 178:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 177;
                  break;
               case 179:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 178;
                  break;
               case 180:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 179;
                  break;
               case 181:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 180;
                  break;
               case 183:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 182;
                  break;
               case 184:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 183;
                  break;
               case 185:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 184;
                  break;
               case 186:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 185;
                  break;
               case 187:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 186;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 188 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   154, 155, 156, 168, 154, 155, 156, 154, 156, 161, 168, 80, 82, 84, 100, 102, 
   103, 106, 107, 158, 159, 160, 92, 98, 174, 176, 181, 187, 134, 135, 141, 145, 
   152, 124, 131, 112, 116, 120, 121, 65, 67, 72, 78, 52, 57, 42, 45, 47, 
   86, 87, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, "\114\111\102\122\101\122\131", "\127\105\102\123\111\124\105", 
"\102\125\111\114\104\111\116\107", "\124\111\115\105\117\106\131\105\101\122", "\123\124\101\122\124", 
"\105\116\104", "\110\117\125\122\123", "\101\115", "\120\115", "\164\157", 
"\103\114\117\123\105\104", "\123\124\101\106\106", "\120\117\123\111\124\111\117\116", 
"\105\115\101\111\114", "\124\131\120\105", null, "\122\101\124\105", 
"\102\117\117\113\103\117\114\114\105\103\124\111\117\116", "\102\117\117\113", "\124\111\124\114\105", "\101\125\124\110\117\122", "\42", 
"\54", "\173", "\175", "\56", "\44", "\50", "\51", null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x6787f57ffffffdL, 
};
static final long[] jjtoSkip = {
   0x2L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[188];
private final int[] jjstateSet = new int[376];
protected char curChar;
/** Constructor. */
public LibParserTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public LibParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 188; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
