/* Generated By:JavaCC: Do not edit this line. LibParserConstants.java */
package lib;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LibParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int LIBRARY = 2;
  /** RegularExpression Id. */
  int WEBSITE = 3;
  /** RegularExpression Id. */
  int BUILDING = 4;
  /** RegularExpression Id. */
  int TIMEOFYEAR = 5;
  /** RegularExpression Id. */
  int START = 6;
  /** RegularExpression Id. */
  int END = 7;
  /** RegularExpression Id. */
  int HOURS = 8;
  /** RegularExpression Id. */
  int AM = 9;
  /** RegularExpression Id. */
  int PM = 10;
  /** RegularExpression Id. */
  int TO = 11;
  /** RegularExpression Id. */
  int CLOSED = 12;
  /** RegularExpression Id. */
  int STAFF = 13;
  /** RegularExpression Id. */
  int POSITION = 14;
  /** RegularExpression Id. */
  int EMAIL = 15;
  /** RegularExpression Id. */
  int TYPE = 16;
  /** RegularExpression Id. */
  int TYPE_VALUE = 17;
  /** RegularExpression Id. */
  int RATE = 18;
  /** RegularExpression Id. */
  int BOOKCOLLECTION = 19;
  /** RegularExpression Id. */
  int BOOK = 20;
  /** RegularExpression Id. */
  int TITLE = 21;
  /** RegularExpression Id. */
  int AUTHOR = 22;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE = 23;
  /** RegularExpression Id. */
  int COMMA = 24;
  /** RegularExpression Id. */
  int LB = 25;
  /** RegularExpression Id. */
  int RB = 26;
  /** RegularExpression Id. */
  int FULL_STOP = 27;
  /** RegularExpression Id. */
  int DOLLAR = 28;
  /** RegularExpression Id. */
  int LP = 29;
  /** RegularExpression Id. */
  int RP = 30;
  /** RegularExpression Id. */
  int AT = 31;
  /** RegularExpression Id. */
  int NAME_GENERAL = 32;
  /** RegularExpression Id. */
  int DIGIT = 33;
  /** RegularExpression Id. */
  int BUILDING_ENTRY = 34;
  /** RegularExpression Id. */
  int PROTOCOL = 35;
  /** RegularExpression Id. */
  int WEBSITE_ENTRY = 36;
  /** RegularExpression Id. */
  int DAY_SHORT = 37;
  /** RegularExpression Id. */
  int DAY = 38;
  /** RegularExpression Id. */
  int MONTH = 39;
  /** RegularExpression Id. */
  int DATE = 40;
  /** RegularExpression Id. */
  int YEAR = 41;
  /** RegularExpression Id. */
  int TIME = 42;
  /** RegularExpression Id. */
  int LETTER_OR_NUMBER = 43;
  /** RegularExpression Id. */
  int EMAIL_LOCAL = 44;
  /** RegularExpression Id. */
  int LETTER_NUMBER_HYPHEN = 45;
  /** RegularExpression Id. */
  int EMAIL_DOMAIN = 46;
  /** RegularExpression Id. */
  int EMAIL_VALUE = 47;
  /** RegularExpression Id. */
  int RATE_VALUE = 48;
  /** RegularExpression Id. */
  int BOOK_ID = 49;
  /** RegularExpression Id. */
  int BOOK_TITLE = 50;
  /** RegularExpression Id. */
  int UPPER_LETTER = 51;
  /** RegularExpression Id. */
  int LETTER = 52;
  /** RegularExpression Id. */
  int AUTHOR_NAME = 53;
  /** RegularExpression Id. */
  int AUTHOR_NAME_INITIAL = 54;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SPACE>",
    "\"LIBRARY\"",
    "\"WEBSITE\"",
    "\"BUILDING\"",
    "\"TIMEOFYEAR\"",
    "\"START\"",
    "\"END\"",
    "\"HOURS\"",
    "\"AM\"",
    "\"PM\"",
    "\"to\"",
    "\"CLOSED\"",
    "\"STAFF\"",
    "\"POSITION\"",
    "\"EMAIL\"",
    "\"TYPE\"",
    "<TYPE_VALUE>",
    "\"RATE\"",
    "\"BOOKCOLLECTION\"",
    "\"BOOK\"",
    "\"TITLE\"",
    "\"AUTHOR\"",
    "\"\\\"\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "\"$\"",
    "\"(\"",
    "\")\"",
    "\"@\"",
    "<NAME_GENERAL>",
    "<DIGIT>",
    "<BUILDING_ENTRY>",
    "<PROTOCOL>",
    "<WEBSITE_ENTRY>",
    "<DAY_SHORT>",
    "<DAY>",
    "<MONTH>",
    "<DATE>",
    "<YEAR>",
    "<TIME>",
    "<LETTER_OR_NUMBER>",
    "<EMAIL_LOCAL>",
    "<LETTER_NUMBER_HYPHEN>",
    "<EMAIL_DOMAIN>",
    "<EMAIL_VALUE>",
    "<RATE_VALUE>",
    "<BOOK_ID>",
    "<BOOK_TITLE>",
    "<UPPER_LETTER>",
    "<LETTER>",
    "<AUTHOR_NAME>",
    "<AUTHOR_NAME_INITIAL>",
  };

}
